// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Keep a sensible default so `prisma generate` works in build environments
    // where DATABASE_URL isn't injected (ex: CI / App Hosting build step).
    url: process.env["DATABASE_URL"] || "file:./dev.db",
  },
});
